### ISSUE TITLE
Error When Try To Preview

### ISSUE THREAD

**Issue by skynomad87** [e-Learning-UMT/essaysimilarity#1]
An error occur when try to preview question suign essay similarity.

Step:
1. Create question suing essay similarity.
2. Preview finish question.
3. Error occur.

![image](https://github.com/e-Learning-UMT/essaysimilarity/assets/99231237/a4f4af71-a99c-4d29-a65a-a5053cae3f78)

**Comment by hafriz** [comment]
update essaysimiliarity to the latest version
